export const API_ROUTES = {
  LOGIN: "/login",
  LOGOUT: "/logout",
  PROFILE: "/profile",
  TRANSACTIONS: "/transactions",
  TRANSACTIONS_DELETED: "/transactions/deleted",
  TRANSACTIONS_ARCHIVE_CANDIDATES: "/transactions/archive-candidates",
  TRANSACTIONS_ARCHIVE: "/transactions/archive",
  ARCHIVED_TRANSACTIONS: "/archived-transactions",
  USERS: "/users",
  CUSTOMERS: "/customers",
  CUSTOMERS_MERGE: "/customers/merge",
  INVENTORY_ITEMS: "/inventory-items",
  INVENTORY_RECORDS: "/inventory-records",
  EXPENSE_ITEMS: "/expense-items",
  EXPENSE_RECORDS: "/expense-records",
  FIXED_MONTHLY_EXPENSES: "/fixed-monthly-expenses",
  BACKUP: "/backup",
  BACKUP_UPLOAD: "/backup/upload",
  BACKUP_SCHEDULE_TIMES: "/backup/schedule-times",
  BACKUP_FOLDER_PATHS: "/backup/folder-paths",
  BACKUPS: "/backups",
  RESTORE: "/restore",
  ADDONS_PRICING: "/addons-pricing",
  ACTIVITY_LOGS: "/activity-logs",
  ACTIVITY_LOG_SETTINGS: "/activity-logs/settings",
  ACTIVITY_LOG_CLEANUP: "/activity-logs/cleanup",
  HOSTING_STATUS: "/hosting/status",
  HOSTING_START: "/hosting/start",
} as const;

export default API_ROUTES;
