const route = {
  ROOT: "/",
  LOGIN: "/login",
  CUSTOMER: "/customer",
  DASHBOARD: "/dashboard",
  TRANSACTION: "/transaction",
  INVENTORY_ITEMS: "/inventory/items",
  INVENTORY_MANAGE: "/inventory/manage",
  INVENTORY_SUMMARY: "/inventory/summary",
  EXPENSES_ITEMS: "/expenses/items",
  EXPENSES_RECORDS: "/expenses/records",
  REPORT_TRANSACTION: "/reports/transaction",
  REPORT_TRANSACTION_SUMMARY: "/reports/transaction-summary",
  REPORT_TRANSACTION_GRAPH_SUMMARY: "/reports/transaction-graph-summary",
  REPORT_CUSTOMER: "/reports/customer",
  REPORT_INVENTORY: "/reports/inventory",
  REPORT_EXPENSES: "/reports/expenses",
  REPORT_SALES: "/reports/sales",
  REPORT_SALES_EXPENSE_GRAPH: "/reports/sales-expense-graph",
  REPORT_COLLECTION: "/reports/collection",
  REPORT_LOAD: "/reports/load",
  REPORT_RECEIVE_RELEASE: "/reports/receive-release",
  USERS: "/users",
  SETTINGS: "/settings/database",
  SETTINGS_ADDONS_PRICING: "/settings/addons-pricing",
  SETTINGS_FIXED_MONTHLY_EXPENSES: "/settings/fixed-monthly-expenses",
  SETTINGS_ACTIVITY_LOG: "/settings/activity-log",
  SETTINGS_DELETED_TRANSACTIONS: "/settings/deleted-transactions",
  SETTINGS_MERGE_CUSTOMER_TRANSACTIONS: "/settings/merge-customer-transactions",
  ARCHIVE_RECORD: "/archive/record",
  ARCHIVE_LISTING: "/archive/listing",
};

export default route;
